# タスクステータス情報
TASK_MITYAKUSYU = 10
TASK_MITYAKUSYU.freeze

TASK_TYAKUSYU = 20
TASK_TYAKUSYU.freeze

TASK_KANRYO = 30
TASK_KANRYO.freeze

TASK_MITYAKUSYU_STR = "未着手"
TASK_MITYAKUSYU_STR.freeze

TASK_TYAKUSYU_STR = "着手"
TASK_MITYAKUSYU_STR.freeze

TASK_KANRYO_STR = "完了"
TASK_MITYAKUSYU_STR.freeze

TASK_STATUS_LIST = { TASK_MITYAKUSYU => TASK_MITYAKUSYU_STR, TASK_TYAKUSYU => TASK_TYAKUSYU_STR, TASK_KANRYO => TASK_KANRYO_STR }
TASK_STATUS_LIST.freeze